//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public int SlNo { get; set; }
        public string AccNo { get; set; }
        public string CallNo { get; set; }
        public string TitleoftheBook { get; set; }
        public string Author { get; set; }
        public string PlaceOfPublishers { get; set; }
        public Nullable<int> Year { get; set; }
        public string Edition { get; set; }
        public string pages { get; set; }
        public string Vol { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
