//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp1 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string PhoneNumber { get; set; }
        public string DepName { get; set; }
        public int HODID { get; set; }
        public int DepID { get; set; }
        public int UniversityID { get; set; }
        public string EmpID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual HOD HOD { get; set; }
    }
}
